M48
; DRILL file {KiCad (6.0.7)} date Thu Aug  4 10:24:48 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-04T10:24:48-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0402
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0935
%
G90
G05
T1
X4.897Y-3.2228
X4.937Y-3.4228
X4.977Y-3.2228
T2
X5.2425Y-2.6709
X5.9701Y-2.6709
T3
X4.837Y-3.2978
X4.837Y-3.4228
X5.037Y-3.2978
X5.037Y-3.4228
T0
M30
